import { VoyageData, HistoryItem, AgentAnalysisResult, AgentAnalysisInput } from './types'

export const getRelativeDate = (daysOffset: number, timeStr = '12:00 IST'): string => {
  const d = new Date()
  d.setDate(d.getDate() + daysOffset)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) + ', ' + timeStr
}

export const getRelativeDateOnly = (daysOffset: number): string => {
  const d = new Date()
  d.setDate(d.getDate() + daysOffset)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

export const DEMO_VOYAGES: Record<string, VoyageData> = {
  'VRK-9021-IN': {
    id: 'v1',
    trackingNumber: 'VRK-9021-IN',
    carrier: 'Maersk Line / Maritime Coastal Feeder',
    vesselName: 'M/V Ocean Sentinel',
    imoNumber: 'IMO 9482710',
    status: 'IN TRANSIT',
    originPort: 'Mumbai (JNPT Nhava Sheva)',
    originCode: 'INBOM',
    destinationPort: 'Chennai (Port Trust East Quay)',
    destinationCode: 'INMAA',
    departureDate: getRelativeDate(-1, '06:30 IST'),
    eta: getRelativeDate(5, '14:00 IST'),
    cargoType: 'Clean Industrial Bulk & Specialty Alloys',
    volume: '450 MT',
    containerCount: '18 × 40ft High Cube',
    currentLocation: 'Off Goa Coast, Arabian Sea',
    coordinates: '15°29\'N, 73°49\'E',
    speed: '14.6 knots',
    heading: '162° SSE',
    distanceRemaining: '420 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Calm seas (Beaufort 2). On schedule for scheduled Chennai harbor pilotage.',
    waypoints: [
      {
        name: 'Nhava Sheva Terminal B',
        code: 'INBOM',
        status: 'completed',
        timestamp: getRelativeDate(-1, '06:30 IST'),
        description: 'Vessel laden & cleared custom clearance berth 4',
        coordinates: '18°56\'N, 72°56\'E',
      },
      {
        name: 'Arabian Sea Coastal Corridor',
        code: 'WAYPOINT-1',
        status: 'completed',
        timestamp: getRelativeDate(-1, '21:15 IST'),
        description: 'Navigated south corridor at 15.1 knots',
        coordinates: '16°42\'N, 73°18\'E',
      },
      {
        name: 'Goa Offshore Meridian',
        code: 'WAYPOINT-2',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Maintaining designated shipping lane; clear visibility',
        coordinates: '15°29\'N, 73°49\'E',
      },
      {
        name: 'Cape Comorin Passage',
        code: 'WAYPOINT-3',
        status: 'upcoming',
        timestamp: getRelativeDate(2, '08:30 IST (Est.)'),
        description: 'Southern tip rounding into Bay of Bengal waters',
        coordinates: '08°04\'N, 77°32\'E',
      },
      {
        name: 'Chennai Outer Anchorage',
        code: 'INMAA',
        status: 'upcoming',
        timestamp: getRelativeDate(5, '14:00 IST (Est.)'),
        description: 'Pilotage boarding & berth allocation at East Terminal',
        coordinates: '13°05\'N, 80°17\'E',
      },
    ],
  },
  'VRK-6140-SG': {
    id: 'v2',
    trackingNumber: 'VRK-6140-SG',
    carrier: 'CMA CGM Global Marine',
    vesselName: 'M/V Pacific Trader',
    imoNumber: 'IMO 9621804',
    status: 'AT PORT',
    originPort: 'Singapore (Pasir Panjang)',
    originCode: 'SGSIN',
    destinationPort: 'Chennai (Port Trust Terminal 2)',
    destinationCode: 'INMAA',
    departureDate: getRelativeDate(-6, '18:00 SGT'),
    eta: getRelativeDate(1, '09:00 IST'),
    cargoType: 'High-Density Electronics & Components',
    volume: '280 MT',
    containerCount: '12 × 40ft HQ',
    currentLocation: 'Chennai Port Outer Anchorage',
    coordinates: '13°06\'N, 80°18\'E',
    speed: '0.2 knots (Anchored)',
    heading: '045° NE',
    distanceRemaining: '4 NM',
    riskLevel: 'Moderate Risk',
    riskDetail: 'Berthing queue delay: 6-hour tidal window wait at Chennai East Gate.',
    waypoints: [
      {
        name: 'Pasir Panjang Terminal',
        code: 'SGSIN',
        status: 'completed',
        timestamp: getRelativeDate(-6, '18:00 SGT'),
        description: 'Departed berth 12 following cargo lash inspection',
        coordinates: '01°16\'N, 103°46\'E',
      },
      {
        name: 'Malacca Strait Transit',
        code: 'SGSIN-PASS',
        status: 'completed',
        timestamp: getRelativeDate(-4, '11:20 SGT'),
        description: 'Cleared traffic separation scheme',
        coordinates: '02°30\'N, 101°40\'E',
      },
      {
        name: 'Bay of Bengal Deep Water',
        code: 'BOB-WAYPOINT',
        status: 'completed',
        timestamp: getRelativeDate(-2, '19:45 IST'),
        description: 'Cruised at steady 16.2 knots',
        coordinates: '09°15\'N, 88°20\'E',
      },
      {
        name: 'Chennai Anchorage Zone',
        code: 'INMAA',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Awaiting pilot tender arrival; harbor tugs assigned',
        coordinates: '13°06\'N, 80°18\'E',
      },
      {
        name: 'Berth 2 Discharging',
        code: 'INMAA-B2',
        status: 'upcoming',
        timestamp: getRelativeDate(1, '15:00 IST (Est.)'),
        description: 'Crane gantry operations commence',
        coordinates: '13°05\'N, 80°17\'E',
      },
    ],
  },
  'VRK-3382-NL': {
    id: 'v3',
    trackingNumber: 'VRK-3382-NL',
    carrier: 'Hapag-Lloyd Express',
    vesselName: 'M/V Atlantic Voyager',
    imoNumber: 'IMO 9385512',
    status: 'COMPLETED',
    originPort: 'Rotterdam (Maasvlakte II)',
    originCode: 'NLRTM',
    destinationPort: 'Mumbai (JNPT Nhava Sheva)',
    destinationCode: 'INBOM',
    departureDate: getRelativeDate(-20, '10:00 CEST'),
    eta: getRelativeDate(-2, '16:30 IST'),
    cargoType: 'Specialized Industrial Machinery & Spares',
    volume: '620 MT',
    containerCount: '24 × 40ft HQ Flat Rack',
    currentLocation: 'JNPT Nhava Sheva Terminal 1',
    coordinates: '18°57\'N, 72°57\'E',
    speed: '0.0 knots (Berthed)',
    heading: 'Moored',
    distanceRemaining: '0 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Voyage discharged successfully. Customs assessment complete.',
    waypoints: [
      {
        name: 'Maasvlakte II',
        code: 'NLRTM',
        status: 'completed',
        timestamp: getRelativeDate(-20, '10:00 CEST'),
        description: 'Outbound North Sea transit initiated',
        coordinates: '51°58\'N, 04°05\'E',
      },
      {
        name: 'Suez Canal Convoy',
        code: 'EGPSD',
        status: 'completed',
        timestamp: getRelativeDate(-12, '14:00 EEST'),
        description: 'Southbound convoy navigation successful',
        coordinates: '29°55\'N, 32°33\'E',
      },
      {
        name: 'Bab-el-Mandeb Strait',
        code: 'YEMEN-CORR',
        status: 'completed',
        timestamp: getRelativeDate(-9, '06:10 UTC'),
        description: 'High-security escort passage completed',
        coordinates: '12°35\'N, 43°20\'E',
      },
      {
        name: 'JNPT Nhava Sheva Berth 1',
        code: 'INBOM',
        status: 'completed',
        timestamp: getRelativeDate(-2, '16:30 IST'),
        description: 'Vessel securely berthed, discharge completed',
        coordinates: '18°57\'N, 72°57\'E',
      },
    ],
  },
  'VRK-8812-CN': {
    id: 'v4',
    trackingNumber: 'VRK-8812-CN',
    carrier: 'COSCO Shipping Lines',
    vesselName: 'M/V Eastern Dawn',
    imoNumber: 'IMO 9781290',
    status: 'DEPARTED',
    originPort: 'Shanghai (Yangshan Deep Water)',
    originCode: 'CNSHA',
    destinationPort: 'Colombo (JCT Terminal)',
    destinationCode: 'LKCMB',
    departureDate: getRelativeDate(-2, '23:45 CST'),
    eta: getRelativeDate(9, '11:00 IST'),
    cargoType: 'Polymers & Chemical Intermediates',
    volume: '510 MT',
    containerCount: '20 × 20ft Tank Container',
    currentLocation: 'East China Sea, Southbound',
    coordinates: '28°14\'N, 122°50\'E',
    speed: '17.4 knots',
    heading: '205° SSW',
    distanceRemaining: '2,180 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Vessel cruising at nominal speed; no weather routing disruptions.',
    waypoints: [
      {
        name: 'Yangshan Terminal Phase 4',
        code: 'CNSHA',
        status: 'completed',
        timestamp: getRelativeDate(-2, '23:45 CST'),
        description: 'Cast off from automated berth 7',
        coordinates: '30°37\'N, 122°03\'E',
      },
      {
        name: 'East China Sea Channel',
        code: 'CNSHA-OUT',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Maintaining full cruising speed southward',
        coordinates: '28°14\'N, 122°50\'E',
      },
      {
        name: 'Taiwan Strait Passage',
        code: 'TW-STR',
        status: 'upcoming',
        timestamp: getRelativeDate(1, '04:00 CST (Est.)'),
        description: 'Scheduled transit corridor entry',
        coordinates: '24°00\'N, 119°30\'E',
      },
      {
        name: 'Singapore Straits Bunker Call',
        code: 'SGSIN',
        status: 'upcoming',
        timestamp: getRelativeDate(4, '12:00 SGT (Est.)'),
        description: 'VLSFO bunkering replenishment stop',
        coordinates: '01°16\'N, 103°50\'E',
      },
      {
        name: 'Colombo Jaya Container Terminal',
        code: 'LKCMB',
        status: 'upcoming',
        timestamp: getRelativeDate(9, '11:00 IST (Est.)'),
        description: 'Final vessel mooring and feeder connection',
        coordinates: '06°57\'N, 79°51\'E',
      },
    ],
  },
}

export const SAMPLE_HISTORY: HistoryItem[] = [
  {
    id: 'h1',
    trackingNumber: 'VRK-9021-IN',
    origin: 'Mumbai (JNPT Nhava Sheva)',
    originCode: 'INBOM',
    destination: 'Chennai (Port Trust East Quay)',
    destinationCode: 'INMAA',
    vessel: 'M/V Ocean Sentinel',
    status: 'IN TRANSIT',
    date: getRelativeDateOnly(-1),
    eta: getRelativeDateOnly(5),
    cargo: 'Clean Industrial Bulk & Specialty Alloys',
    volume: '450 MT (18 FEU)',
  },
  {
    id: 'h2',
    trackingNumber: 'VRK-6140-SG',
    origin: 'Singapore (Pasir Panjang)',
    originCode: 'SGSIN',
    destination: 'Chennai (Port Trust Terminal 2)',
    destinationCode: 'INMAA',
    vessel: 'M/V Pacific Trader',
    status: 'AT PORT',
    date: getRelativeDateOnly(-6),
    eta: getRelativeDateOnly(1),
    cargo: 'High-Density Electronics',
    volume: '280 MT (12 FEU)',
  },
  {
    id: 'h3',
    trackingNumber: 'VRK-3382-NL',
    origin: 'Rotterdam (Maasvlakte II)',
    originCode: 'NLRTM',
    destination: 'Mumbai (JNPT Nhava Sheva)',
    destinationCode: 'INBOM',
    vessel: 'M/V Atlantic Voyager',
    status: 'COMPLETED',
    date: getRelativeDateOnly(-20),
    eta: `${getRelativeDateOnly(-2)} (Arrived)`,
    cargo: 'Specialized Industrial Machinery',
    volume: '620 MT (24 FEU)',
  },
  {
    id: 'h4',
    trackingNumber: 'VRK-8812-CN',
    origin: 'Shanghai (Yangshan Deep Water)',
    originCode: 'CNSHA',
    destination: 'Colombo (JCT Terminal)',
    destinationCode: 'LKCMB',
    vessel: 'M/V Eastern Dawn',
    status: 'DEPARTED',
    date: getRelativeDateOnly(-2),
    eta: getRelativeDateOnly(9),
    cargo: 'Polymers & Chemical Intermediates',
    volume: '510 MT (20 TEU)',
  },
]

export const SAMPLE_AGENT_INPUT: AgentAnalysisInput = {
  origin: '',
  destination: '',
  cargoType: '',
  cargoVolume: '',
  containerType: '40ft High Cube (FEU)',
  quotedRate: '',
}

export const SAMPLE_AGENT_RESULT: AgentAnalysisResult = {
  quotedRate: 2850,
  estimatedMinLandedCost: 3260,
  estimatedMaxLandedCost: 3510,
  variancePercent: 18.2,
  timestamp: 'Calculated from live freight indices',
  hiddenCosts: [
    {
      id: 'hc-1',
      category: 'Demurrage & Detention',
      code: 'DEM-DEST',
      estimatedMin: 220,
      estimatedMax: 380,
      riskLevel: 'Moderate',
      explanation: 'Destination terminal average dwell time (9.2 days) exceeds standard 7-day free detention allowance.',
      tacticalAdvice: 'Pre-negotiate 14 free detention days during carrier booking nomination to prevent post-discharge penalties.',
    },
    {
      id: 'hc-2',
      category: 'Terminal Accessorials',
      code: 'THC-DEST',
      estimatedMin: 140,
      estimatedMax: 180,
      riskLevel: 'Low',
      explanation: 'Destination East Quay terminal lift & grounding surcharge assessed separately from base ocean carriage.',
      tacticalAdvice: 'Confirm liner-out terms with the carrier so destination terminal handling charges are explicitly covered in bill of lading.',
    },
    {
      id: 'hc-3',
      category: 'Bunker Volatility Index',
      code: 'BAF-ADJ',
      estimatedMin: 50,
      estimatedMax: 100,
      riskLevel: 'Low',
      explanation: 'Mid-voyage bunker fuel price index adjustment floating on quarterly Brent marine gasoil averages.',
      tacticalAdvice: 'Lock bunker adjustment factor (BAF) at time of fixture with a floating floor collar clause.',
    },
  ],
}
