import { VoyageData, HistoryItem, AgentAnalysisResult, AgentAnalysisInput } from './types'

export const DEMO_VOYAGES: Record<string, VoyageData> = {
  'VRK-9021-IN': {
    id: 'v1',
    trackingNumber: 'VRK-9021-IN',
    carrier: 'Maersk Line / Maritime Coastal Feeder',
    vesselName: 'M/V Ocean Sentinel',
    imoNumber: 'IMO 9482710',
    status: 'IN TRANSIT',
    originPort: 'Mumbai (JNPT Nhava Sheva)',
    originCode: 'INBOM',
    destinationPort: 'Chennai (Port Trust East Quay)',
    destinationCode: 'INMAA',
    departureDate: '12 Sep 2026, 06:30 IST',
    eta: '18 Sep 2026, 14:00 IST',
    cargoType: 'Clean Industrial Bulk & Specialty Alloys',
    volume: '450 MT',
    containerCount: '18 × 40ft High Cube',
    currentLocation: 'Off Goa Coast, Arabian Sea',
    coordinates: '15°29\'N, 73°49\'E',
    speed: '14.6 knots',
    heading: '162° SSE',
    distanceRemaining: '420 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Calm seas (Beaufort 2). On schedule for scheduled Chennai harbor pilotage.',
    waypoints: [
      {
        name: 'Nhava Sheva Terminal B',
        code: 'INBOM',
        status: 'completed',
        timestamp: '12 Sep 2026, 06:30 IST',
        description: 'Vessel laden & cleared custom clearance berth 4',
        coordinates: '18°56\'N, 72°56\'E',
      },
      {
        name: 'Arabian Sea Coastal Corridor',
        code: 'WAYPOINT-1',
        status: 'completed',
        timestamp: '12 Sep 2026, 21:15 IST',
        description: 'Navigated south corridor at 15.1 knots',
        coordinates: '16°42\'N, 73°18\'E',
      },
      {
        name: 'Goa Offshore Meridian',
        code: 'WAYPOINT-2',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Maintaining designated shipping lane; clear visibility',
        coordinates: '15°29\'N, 73°49\'E',
      },
      {
        name: 'Cape Comorin Passage',
        code: 'WAYPOINT-3',
        status: 'upcoming',
        timestamp: '15 Sep 2026, 08:30 IST (Est.)',
        description: 'Southern tip rounding into Bay of Bengal waters',
        coordinates: '08°04\'N, 77°32\'E',
      },
      {
        name: 'Chennai Outer Anchorage',
        code: 'INMAA',
        status: 'upcoming',
        timestamp: '18 Sep 2026, 14:00 IST (Est.)',
        description: 'Pilotage boarding & berth allocation at East Terminal',
        coordinates: '13°05\'N, 80°17\'E',
      },
    ],
  },
  'VRK-6140-SG': {
    id: 'v2',
    trackingNumber: 'VRK-6140-SG',
    carrier: 'CMA CGM Global Marine',
    vesselName: 'M/V Pacific Trader',
    imoNumber: 'IMO 9621804',
    status: 'AT PORT',
    originPort: 'Singapore (Pasir Panjang)',
    originCode: 'SGSIN',
    destinationPort: 'Chennai (Port Trust Terminal 2)',
    destinationCode: 'INMAA',
    departureDate: '07 Sep 2026, 18:00 SGT',
    eta: '14 Sep 2026, 09:00 IST',
    cargoType: 'High-Density Electronics & Components',
    volume: '280 MT',
    containerCount: '12 × 40ft HQ',
    currentLocation: 'Chennai Port Outer Anchorage',
    coordinates: '13°06\'N, 80°18\'E',
    speed: '0.2 knots (Anchored)',
    heading: '045° NE',
    distanceRemaining: '4 NM',
    riskLevel: 'Moderate Risk',
    riskDetail: 'Berthing queue delay: 6-hour tidal window wait at Chennai East Gate.',
    waypoints: [
      {
        name: 'Pasir Panjang Terminal',
        code: 'SGSIN',
        status: 'completed',
        timestamp: '07 Sep 2026, 18:00 SGT',
        description: 'Departed berth 12 following cargo lash inspection',
        coordinates: '01°16\'N, 103°46\'E',
      },
      {
        name: 'Malacca Strait Transit',
        code: 'SGSIN-PASS',
        status: 'completed',
        timestamp: '09 Sep 2026, 11:20 SGT',
        description: 'Cleared traffic separation scheme',
        coordinates: '02°30\'N, 101°40\'E',
      },
      {
        name: 'Bay of Bengal Deep Water',
        code: 'BOB-WAYPOINT',
        status: 'completed',
        timestamp: '11 Sep 2026, 19:45 IST',
        description: 'Cruised at steady 16.2 knots',
        coordinates: '09°15\'N, 88°20\'E',
      },
      {
        name: 'Chennai Anchorage Zone',
        code: 'INMAA',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Awaiting pilot tender arrival; harbor tugs assigned',
        coordinates: '13°06\'N, 80°18\'E',
      },
      {
        name: 'Berth 2 Discharging',
        code: 'INMAA-B2',
        status: 'upcoming',
        timestamp: '14 Sep 2026, 15:00 IST (Est.)',
        description: 'Crane gantry operations commence',
        coordinates: '13°05\'N, 80°17\'E',
      },
    ],
  },
  'VRK-3382-NL': {
    id: 'v3',
    trackingNumber: 'VRK-3382-NL',
    carrier: 'Hapag-Lloyd Express',
    vesselName: 'M/V Atlantic Voyager',
    imoNumber: 'IMO 9385512',
    status: 'COMPLETED',
    originPort: 'Rotterdam (Maasvlakte II)',
    originCode: 'NLRTM',
    destinationPort: 'Mumbai (JNPT Nhava Sheva)',
    destinationCode: 'INBOM',
    departureDate: '24 Aug 2026, 10:00 CEST',
    eta: '11 Sep 2026, 16:30 IST',
    cargoType: 'Specialized Industrial Machinery & Spares',
    volume: '620 MT',
    containerCount: '24 × 40ft HQ Flat Rack',
    currentLocation: 'JNPT Nhava Sheva Terminal 1',
    coordinates: '18°57\'N, 72°57\'E',
    speed: '0.0 knots (Berthed)',
    heading: 'Moored',
    distanceRemaining: '0 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Voyage discharged successfully. Customs assessment complete.',
    waypoints: [
      {
        name: 'Maasvlakte II',
        code: 'NLRTM',
        status: 'completed',
        timestamp: '24 Aug 2026, 10:00 CEST',
        description: 'Outbound North Sea transit initiated',
        coordinates: '51°58\'N, 04°05\'E',
      },
      {
        name: 'Suez Canal Convoy',
        code: 'EGPSD',
        status: 'completed',
        timestamp: '01 Sep 2026, 14:00 EEST',
        description: 'Southbound convoy navigation successful',
        coordinates: '29°55\'N, 32°33\'E',
      },
      {
        name: 'Bab-el-Mandeb Strait',
        code: 'YEMEN-CORR',
        status: 'completed',
        timestamp: '04 Sep 2026, 06:10 UTC',
        description: 'High-security escort passage completed',
        coordinates: '12°35\'N, 43°20\'E',
      },
      {
        name: 'JNPT Nhava Sheva Berth 1',
        code: 'INBOM',
        status: 'completed',
        timestamp: '11 Sep 2026, 16:30 IST',
        description: 'Vessel securely berthed, discharge completed',
        coordinates: '18°57\'N, 72°57\'E',
      },
    ],
  },
  'VRK-8812-CN': {
    id: 'v4',
    trackingNumber: 'VRK-8812-CN',
    carrier: 'COSCO Shipping Lines',
    vesselName: 'M/V Eastern Dawn',
    imoNumber: 'IMO 9781290',
    status: 'DEPARTED',
    originPort: 'Shanghai (Yangshan Deep Water)',
    originCode: 'CNSHA',
    destinationPort: 'Colombo (JCT Terminal)',
    destinationCode: 'LKCMB',
    departureDate: '11 Sep 2026, 23:45 CST',
    eta: '22 Sep 2026, 11:00 IST',
    cargoType: 'Polymers & Chemical Intermediates',
    volume: '510 MT',
    containerCount: '20 × 20ft Tank Container',
    currentLocation: 'East China Sea, Southbound',
    coordinates: '28°14\'N, 122°50\'E',
    speed: '17.4 knots',
    heading: '205° SSW',
    distanceRemaining: '2,180 NM',
    riskLevel: 'Low Risk',
    riskDetail: 'Vessel cruising at nominal speed; no weather routing disruptions.',
    waypoints: [
      {
        name: 'Yangshan Terminal Phase 4',
        code: 'CNSHA',
        status: 'completed',
        timestamp: '11 Sep 2026, 23:45 CST',
        description: 'Cast off from automated berth 7',
        coordinates: '30°37\'N, 122°03\'E',
      },
      {
        name: 'East China Sea Channel',
        code: 'CNSHA-OUT',
        status: 'current',
        timestamp: 'Live Coordinate',
        description: 'Maintaining full cruising speed southward',
        coordinates: '28°14\'N, 122°50\'E',
      },
      {
        name: 'Taiwan Strait Passage',
        code: 'TW-STR',
        status: 'upcoming',
        timestamp: '14 Sep 2026, 04:00 CST (Est.)',
        description: 'Scheduled transit corridor entry',
        coordinates: '24°00\'N, 119°30\'E',
      },
      {
        name: 'Singapore Straits Bunker Call',
        code: 'SGSIN',
        status: 'upcoming',
        timestamp: '17 Sep 2026, 12:00 SGT (Est.)',
        description: 'VLSFO bunkering replenishment stop',
        coordinates: '01°16\'N, 103°50\'E',
      },
      {
        name: 'Colombo Jaya Container Terminal',
        code: 'LKCMB',
        status: 'upcoming',
        timestamp: '22 Sep 2026, 11:00 IST (Est.)',
        description: 'Final vessel mooring and feeder connection',
        coordinates: '06°57\'N, 79°51\'E',
      },
    ],
  },
}

export const SAMPLE_HISTORY: HistoryItem[] = [
  {
    id: 'h1',
    trackingNumber: 'VRK-9021-IN',
    origin: 'Mumbai (JNPT Nhava Sheva)',
    originCode: 'INBOM',
    destination: 'Chennai (Port Trust East Quay)',
    destinationCode: 'INMAA',
    vessel: 'M/V Ocean Sentinel',
    status: 'IN TRANSIT',
    date: '12 Sep 2026',
    eta: '18 Sep 2026',
    cargo: 'Clean Industrial Bulk & Specialty Alloys',
    volume: '450 MT (18 FEU)',
  },
  {
    id: 'h2',
    trackingNumber: 'VRK-6140-SG',
    origin: 'Singapore (Pasir Panjang)',
    originCode: 'SGSIN',
    destination: 'Chennai (Port Trust Terminal 2)',
    destinationCode: 'INMAA',
    vessel: 'M/V Pacific Trader',
    status: 'AT PORT',
    date: '07 Sep 2026',
    eta: '14 Sep 2026',
    cargo: 'High-Density Electronics',
    volume: '280 MT (12 FEU)',
  },
  {
    id: 'h3',
    trackingNumber: 'VRK-3382-NL',
    origin: 'Rotterdam (Maasvlakte II)',
    originCode: 'NLRTM',
    destination: 'Mumbai (JNPT Nhava Sheva)',
    destinationCode: 'INBOM',
    vessel: 'M/V Atlantic Voyager',
    status: 'COMPLETED',
    date: '24 Aug 2026',
    eta: '11 Sep 2026 (Arrived)',
    cargo: 'Specialized Industrial Machinery',
    volume: '620 MT (24 FEU)',
  },
  {
    id: 'h4',
    trackingNumber: 'VRK-8812-CN',
    origin: 'Shanghai (Yangshan Deep Water)',
    originCode: 'CNSHA',
    destination: 'Colombo (JCT Terminal)',
    destinationCode: 'LKCMB',
    vessel: 'M/V Eastern Dawn',
    status: 'DEPARTED',
    date: '11 Sep 2026',
    eta: '22 Sep 2026',
    cargo: 'Polymers & Chemical Intermediates',
    volume: '510 MT (20 TEU)',
  },
]

export const SAMPLE_AGENT_INPUT: AgentAnalysisInput = {
  origin: 'Mumbai (JNPT Nhava Sheva, India)',
  destination: 'Chennai (Port Trust East Terminal, India)',
  cargoType: 'Industrial Heavy Machinery & Steel Components',
  cargoVolume: '450 MT / 18 Units',
  containerType: '40ft High Cube (FEU)',
  quotedRate: 2850,
}

export const SAMPLE_AGENT_RESULT: AgentAnalysisResult = {
  quotedRate: 2850,
  currency: 'USD',
  estimatedMinLandedCost: 3260,
  estimatedMaxLandedCost: 3410,
  variancePercent: 16.8,
  riskIndex: 'Moderate',
  timestamp: 'Analysis computed on benchmark freight model',
  isSimulated: true,
  costCategories: [
    {
      id: 'c1',
      category: 'Port Charges & Terminal Handling (THC)',
      code: 'THC-DEST',
      estimatedMin: 180,
      estimatedMax: 240,
      riskLevel: 'Moderate',
      explanation: 'Destination terminal handling tariff update effective Q3. Unquoted gantry move fee at Chennai East Berth.',
      tacticalAdvice: 'Require line-item quote inclusion for Chennai THC and verify whether stevedoring crane tariff is absorbed in standard ocean bill.',
    },
    {
      id: 'c2',
      category: 'Demurrage & Dwell Risk Buffer',
      code: 'DEM-RISK',
      estimatedMin: 120,
      estimatedMax: 190,
      riskLevel: 'High',
      explanation: 'Average discharge dwell time at Chennai currently sits at 5.2 days against standard carrier free time of 3.0 days.',
      tacticalAdvice: 'Pre-negotiate 7 calendar days of free demurrage prior to booking confirmation to eliminate gate queue exposure.',
    },
    {
      id: 'c3',
      category: 'Customs & Bonded Verification Dues',
      code: 'CUST-EXAM',
      estimatedMin: 65,
      estimatedMax: 95,
      riskLevel: 'Low',
      explanation: 'Mandatory special equipment scanning and Customs EDI gateway verification charges for heavy machinery.',
      tacticalAdvice: 'Ensure bill of lading HS classification is pre-filed 48h prior to harbor arrival to prevent secondary inspection triage.',
    },
    {
      id: 'c4',
      category: 'Documentation & Electronic Manifest Filing',
      code: 'DOCS-EDI',
      estimatedMin: 35,
      estimatedMax: 50,
      riskLevel: 'Low',
      explanation: 'Advance cargo declaration manifest amendment buffers and carrier electronic delivery order (e-DO) release fees.',
      tacticalAdvice: 'Consolidate multiple container manifests into a single master delivery order to reduce per-box filing overhead.',
    },
    {
      id: 'c5',
      category: 'Detention & Turnaround Contingency',
      code: 'DET-BUF',
      estimatedMin: 80,
      estimatedMax: 130,
      riskLevel: 'Moderate',
      explanation: 'Empty container repositioning turnaround delays at inland container depot (ICD) during peak monsoon season.',
      tacticalAdvice: 'Specify off-dock empty drop facility in the booking contract rather than deep port gate returns.',
    },
    {
      id: 'c6',
      category: 'Inland Drayage & Haulage Fuel Factor',
      code: 'DRAY-FUEL',
      estimatedMin: 90,
      estimatedMax: 140,
      riskLevel: 'Low',
      explanation: 'Toll plaza revisions and state highway drayage fuel adjustment factor on regional haulage from quay to warehouse.',
      tacticalAdvice: 'Contract drayage at a fixed all-in lump sum inclusive of national highway toll surcharges.',
    },
    {
      id: 'c7',
      category: 'Bunker Adjustment & Low-Sulfur Factor (BAF)',
      code: 'BAF-ADJ',
      estimatedMin: 40,
      estimatedMax: 65,
      riskLevel: 'Low',
      explanation: 'Monthly fuel escalation clause applied by regional coastal feeder operators.',
      tacticalAdvice: 'Verify whether quoted ocean freight is on "BAF-inclusive" terms or subject to end-of-month carrier adjustment index.',
    },
  ],
  keyRecommendations: [
    'Secure 7-10 days free detention/demurrage at Chennai to buffer against harbor gate dwell.',
    'Confirm that Terminal Handling Charges (THC) at both origin (JNPT) and destination (Chennai) are all-in.',
    'Pre-lodge electronic customs declaration 48 hours before coastal arrival to ensure immediate direct port delivery (DPD) clearance.',
    'Lock fuel surcharge (BAF) against volatility indices for contracts exceeding 30 calendar days.',
  ],
}
